"""remove_api_key_from_users_table

Revision ID: 6ee1a8575943
Revises: add_api_key_to_users
Create Date: 2025-10-01 16:22:44.076398

"""
from typing import Iterable

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ee1a8575943'
down_revision = 'add_api_key_to_users'
branch_labels = None
depends_on = None


def _has_fk(
    fks: Iterable[dict],
    constrained_columns: list[str],
    referred_table: str,
) -> bool:
    constrained = set(constrained_columns)
    return any(
        set(fk.get("constrained_columns") or []) == constrained
        and fk.get("referred_table") == referred_table
        for fk in fks
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "ALTER TABLE executions "
            "ADD COLUMN IF NOT EXISTS session_id VARCHAR(255)"
        )
    )

    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table("agent_tools"):
        agent_tools_columns = {col["name"] for col in inspector.get_columns("agent_tools")}
        agent_tools_indexes = {idx["name"] for idx in inspector.get_indexes("agent_tools")}
        agent_tools_fks = inspector.get_foreign_keys("agent_tools")

        if "config" in agent_tools_columns:
            op.alter_column(
                "agent_tools",
                "config",
                existing_type=postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
            )

        if "ix_agent_tools_id" in agent_tools_indexes:
            op.drop_index(op.f("ix_agent_tools_id"), table_name="agent_tools")

        if (
            not _has_fk(agent_tools_fks, ["tool_id"], "tools")
            and "tool_id" in agent_tools_columns
        ):
            op.create_foreign_key(
                None, "agent_tools", "tools", ["tool_id"], ["id"], ondelete="CASCADE"
            )

        if (
            not _has_fk(agent_tools_fks, ["agent_id"], "agents")
            and "agent_id" in agent_tools_columns
        ):
            op.create_foreign_key(
                None, "agent_tools", "agents", ["agent_id"], ["id"], ondelete="CASCADE"
            )

        if "id" in agent_tools_columns:
            op.drop_column("agent_tools", "id")

    if inspector.has_table("agents"):
        agent_fks = inspector.get_foreign_keys("agents")
        agent_columns = {col["name"] for col in inspector.get_columns("agents")}
        if "user_id" in agent_columns and not _has_fk(agent_fks, ["user_id"], "users"):
            op.create_foreign_key(
                None, "agents", "users", ["user_id"], ["id"], ondelete="CASCADE"
            )

    if inspector.has_table("auth_tokens"):
        auth_fks = inspector.get_foreign_keys("auth_tokens")
        auth_columns = {col["name"] for col in inspector.get_columns("auth_tokens")}
        if "user_id" in auth_columns and not _has_fk(auth_fks, ["user_id"], "users"):
            op.create_foreign_key(
                None, "auth_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
            )

    if inspector.has_table("embeddings"):
        embedding_fks = inspector.get_foreign_keys("embeddings")
        embedding_columns = {col["name"] for col in inspector.get_columns("embeddings")}
        if "agent_id" in embedding_columns and not _has_fk(
            embedding_fks, ["agent_id"], "agents"
        ):
            op.create_foreign_key(
                None, "embeddings", "agents", ["agent_id"], ["id"], ondelete="CASCADE"
            )

    if inspector.has_table("executions"):
        execution_columns = {col["name"] for col in inspector.get_columns("executions")}
        execution_indexes = {idx["name"] for idx in inspector.get_indexes("executions")}
        execution_fks = inspector.get_foreign_keys("executions")

        if (
            "session_id" in execution_columns
            and "ix_executions_session_id" not in execution_indexes
        ):
            op.create_index(
                op.f("ix_executions_session_id"),
                "executions",
                ["session_id"],
                unique=False,
            )

        if "agent_id" in execution_columns and not _has_fk(
            execution_fks, ["agent_id"], "agents"
        ):
            op.create_foreign_key(
                None, "executions", "agents", ["agent_id"], ["id"], ondelete="CASCADE"
            )

    if inspector.has_table("users"):
        user_columns = {col["name"] for col in inspector.get_columns("users")}
        if "created_at" in user_columns:
            op.alter_column(
                "users",
                "created_at",
                existing_type=postgresql.TIMESTAMP(timezone=True),
                nullable=False,
                existing_server_default=sa.text("now()"),
            )

        user_constraints = {uc["name"] for uc in inspector.get_unique_constraints("users")}
        if "uq_users_api_key" in user_constraints:
            op.drop_constraint(op.f("uq_users_api_key"), "users", type_="unique")

        if "api_key" in user_columns:
            op.drop_column("users", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_users_api_key'), 'users', ['api_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'executions', type_='foreignkey')
    op.drop_index(op.f('ix_executions_session_id'), table_name='executions')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_constraint(None, 'auth_tokens', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.add_column('agent_tools', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.drop_constraint(None, 'agent_tools', type_='foreignkey')
    op.create_index(op.f('ix_agent_tools_id'), 'agent_tools', ['id'], unique=False)
    op.alter_column('agent_tools', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
